# Tema: NumPy



**¿Qué es NumPy?**

Numerical Python es una biblioteca de Python especializada en el cálculo y el manejo de arreglos multidimensionales. Fue diseñada para realizar operaciones matemáticas de manera rápida y eficiente, siendo una de las herramientas más utilizadas en ciencia de datos, inteligencia artificial, ingeniería y análisis de información. Su principal característica es el uso de los arreglos, los cuales permiten almacenar cantidades de datos y realizar operaciones sobre todos sus elementos al mismo tiempo, sin necesidad de utilizar múltiples ciclos.

**¿Para qué sirve?**

Se utiliza para facilitar el procesamiento de datos numéricos. Entre sus principales aplicaciones están el crear vectores y matrices, realizar operaciones matemáticas entre arreglos, resolver cálculos estadísticos, manipular datos multidimensionales, trabajar con álgebra linea, generar números aleatorios y servir como base para otras bibliotecas como Pandas, SciPy, TensorFlow y Scikit-Learn.

Gracias a su optimización, NumPy ejecuta operaciones mucho más rápido que las lsitas tradicionales de Pyhton.

In [ ]:
# ¿Cómo se utiliza o implementa?

# Primero debe instalarse la biblioteca (si es necesario)
!pip install numpy

# Luego se importar dentro del programa.
import numpy as np

# Después pueden crearse arreglos utilizando la función array(). Por ejemplo:
arreglo = np.array([10, 15, 20, 25, 5])
print("Arreglo:", arreglo)
multiplicacion = arreglo * 2
print("Arreglo multiplicado por 2:", multiplicacion)

Arreglo: [10 15 20 25  5]
Arreglo multiplicado por 2: [20 30 40 50 10]


In [ ]:
# Ejemplo 1
import numpy as np

notas = np.array([9, 8, 10, 7, 9])

promedio = np.mean(notas)

print("Notas:", notas)
print("Promedio:", promedio)


# Explicación: se crear un arreglo con cinco calificaciones y posteriormente se utiliza la función mean () para calcular automáticamente el promedio de todos los valores.

Notas: [ 9  8 10  7  9]
Promedio: 8.6


In [ ]:
# Ejemplo 2
import numpy as np

A = np.array([[2, 4],
              [6, 8]])

B = np.array([[1, 3],
              [5, 7]])

suma = A + B
multiplicacion = A * B
print("Matriz A")
print(A)

print("Matriz B")
print(B)

print("Suma")
print(suma)

print("Multiplicación elemento por elemento")
print(multiplicacion)

Matriz A
[[2 4]
 [6 8]]
Matriz B
[[1 3]
 [5 7]]
Suma
[[ 3  7]
 [11 15]]
Multiplicación elemento por elemento
[[ 2 12]
 [30 56]]


**Conclusión**

NumPy es una de las bibliotecas más importantes de Python debido a que permite realizar cálculos numéricos de forma rápida y eficiente. Sus arreglos optimizados reducen el tiempo de ejecución y simplifican la programación de operaciones matemáticas, siendo ampliamente utilizada en proyectos de análisis de datosm inteligencia artificial y computación científica.